### ISSUE TITLE
HC165

### ISSUE THREAD

**Issue by lazenyuk-dmitry** [vsulako/AFFBWheel#15]
Привет. Я тут подключил кнопки пока только по 1линии (DATA1)

И они работают но не правильно. У меня постоянно нажата кнопка 9 а вместо кнопки 13(вроде бы 13) нажимается кнопка 1.
И перепутаны кнопки вместо кнопки 1 нажимается 2 и тд 2 это 3, 3-4, 4-5....

Я использую  `SN74HC165N`. 
![IMG_20220629_191810](https://user-images.githubusercontent.com/31993282/176448214-a1bfc271-d9c4-41ee-89f3-d6f322818566.jpg)

В чем может быть дело. Вроде собрано все правильно. Или у меня неправильный какой то HC165 но я нашел только такой.
Не охото все разматывать) Но вроде все правильно. Как будто смещены кнопки.

**Comment by vsulako** [comment]
ой, похоже закралась ошибка. Обновил код, попробуйте теперь.

**Comment by lazenyuk-dmitry** [comment]
Вот здесь https://github.com/vsulako/AFFBWheel/commit/4360836bd9587b872d9a16cf1384bb67b19e3e8c инпут лаг у кнопок начинается, в этом коммите.

**Comment by vsulako** [comment]
странно. я лага не наблюдаю. и коммит этот никак с кнопками не связан...
а если загрузить настройки по умолчанию?

**Comment by lazenyuk-dmitry** [comment]
У меня похоже как то выставился Debounce у кнопок, я не выставлял. Теперь все нормально) Спасибо.
