### ISSUE TITLE
Совместимость с оптическим энкодером

### ISSUE THREAD

**Issue by Mozasvit** [vsulako/AFFBWheel#20]
Возможно ли, использовать в качестве энкодера родной оптический энкодер?

**Comment by vsulako** [comment]
Родной - то есть от руля? насколько я знаю, там обычные энкодеры и используются, так что должно работать.

**Comment by lazenyuk-dmitry** [comment]
@Mozasvit , не понятно немного, про что вы? Вы хотите оптический энкодер как в принтере использовать? На схеме энкодер тоже оптический. Принцып лишь бы был одинаков '+', '-' и фазы 'А' и 'В'.

Вот схема с энкодером от принтера но это из другого проекта. Но принцып тот же. 

http://steeringwheel.aggress.ru/index.php?cmtx_sort=2&fl=electro

![leonardo.jpg](https://user-images.githubusercontent.com/31993282/182208561-e7cdc6d1-0c73-46c1-b313-0ebffed55bd8.jpg)

**Comment by Mozasvit** [comment]
Здравствуйте, я не электронщик. Вот и интересуюсь. Нашел проект на странице мододелов Logitech MOMO.
В руле используется оптический энкодер,  а в описании оговариваются инкрементальные и магнитные.

**Comment by vsulako** [comment]
Это разные свойства. 
Есть инкрементальные, а есть абсолютные, отличаются тем что у абсолютных есть определенное нулевое положение, они сложнее, дороже, и подключаются тоже сложнее. 
Скорее всего, у вас и есть инкрементальный оптический энкодер. У него должен быть диск со щелями, которые расположены в радиальном направлении - от центра к краям, без каких-либо мудреных рисунков. Количество этих щелей на диске - PPR энкодера. И 4-5 выходов: плюс, минус, и два-три датчика, скорее два чем три.

**Comment by Mozasvit** [comment]
Так и есть!
Спасибо!
