### ISSUE TITLE
Сдвиговые регистры.

### ISSUE THREAD

**Issue by Mozasvit** [vsulako/AFFBWheel#21]
Здравствуйте. Это снова я - неэлектронщик.

В инструкции написано брать 4 сдвиговых регистра 74hc165. На AliExpress продаются всякие разные. Взял sn74hc165n. Они подходят, или надо другие искать?

**Comment by lazenyuk-dmitry** [comment]
@Mozasvit, у меня такие же. Все работает отлично. 

![IMG_20220629_191810.jpg](https://user-images.githubusercontent.com/31993282/184809093-0e49e27b-52b4-4e66-9903-331d48679b60.jpg)

**Comment by Mozasvit** [comment]
Я собрал частичный макет схемы, но руль выдает какую то ахинею.

**Comment by lazenyuk-dmitry** [comment]
Если интересно, я распаявал сразу на минус перемычку и сопротивления 10к сразу на регистре а потом припаявал провода. Так удобнее. Фото жаль нету.

**Comment by lazenyuk-dmitry** [comment]
> Я собрал частичный макет схемы, но руль выдает какую то ахинею.

Какую?

**Comment by Mozasvit** [comment]
Фото будет позже. Нет доступа.

Показания энкодера руля скачут как бешеные. Допускаю неправильное подключение его в схему, там немного иная цветовая маркировка.

Показания осей педалей скачут. Возможно из-за шума. Я подцепил для пробы только один потенциометр.

Но GUI приложение из описания говорит мне, что кнопки 25, 26 нажаты, хотя кнопки не подключались вообще.

**Comment by vsulako** [comment]
> В инструкции написано брать 4 сдвиговых регистра 74hc165. На AliExpress продаются всякие разные. Взял sn74hc165n. Они подходят, или надо другие искать?

Если в названии есть 74hc165 - это все одно и то же: https://www.chipfind.ru/crossreference/search.htm?s=74hc165 (разница в производителе и в несущественных мелочах)
Но для неэлектронщика, наверное, было бы проще использовать I2c расширители - меньше соединений и меньше возможности что-то напутать.

**Comment by Mozasvit** [comment]
С учётом времени на доставку китайцами, этот вариант я опробую не скоро.

**Comment by vsulako** [comment]
С энкодером: попробуйте добавить подтяжки на линии A и B энкодера. (т.е. резисторы 1-10кОм, от A/B к +5в)
С осями: неподключенные оси будут ловить шум, а что с подключенной?
С кнопками: вы случайно не включили ли функцию аналоговых кнопок? (не раскомментировано ли `#define APB`) В файле конфигурации для примера как раз стоят кнопки 25 и 26.

**Comment by Mozasvit** [comment]
Аналоговы кнопки в настройках вроде не  трогал.

Позже проверю все методы. Сейчас нет доступа к плате.

Потенциометр, подключенный к пину педали газа, не реагирует на прокручивания.

**Comment by Mozasvit** [comment]
Ещё нюанс.
Я как истинный неэлектронщик развел плату для этого проекта.
Это могло сказаться на конечном результате

**Comment by lazenyuk-dmitry** [comment]
> Ещё нюанс.
> Я как истинный неэлектронщик развел плату для этого проекта.
> Это могло сказаться на конечном результате?

Что значит "развел плату"?

**Comment by lazenyuk-dmitry** [comment]
> Показания осей педалей скачут. Возможно из-за шума. Я подцепил для пробы только один потенциометр.

В GUI можно пока отключить не используемые оси. Там галочка ставиться. Чтобы не мешало.

**Comment by Mozasvit** [comment]
Я - "нарисовал", китайцы - "распечатали".

**Comment by lazenyuk-dmitry** [comment]
> Потенциометр, подключенный к пину педали газа, не реагирует на прокручивания.

Странно. Если можете покажите как подключили.

**Comment by Mozasvit** [comment]
Все посмотрю когда прийду домой.
Спасибо.
