### ISSUE TITLE
Что то не понятное с кнопками.

### ISSUE THREAD

**Issue by lazenyuk-dmitry** [vsulako/AFFBWheel#25]
@vsulako, привет. Я тут сделал КПП это кнопки с 17 по 32. Теперь при подключении КПП перестают работать кнопки на руле 9-16, работает только 16 кнопка а 15 кнопка тригерит кнопку 9... Вобще какая то дичь. После отключения КПП все нормально. 
На на КПП у меня кнопки 17,19 и 18,20 это преключатели ВКЛ-ВКЛ. Теперь когда нажимаю 29 кнопку то все остальные отключаются, а при нажатии  кнопки 28 включается 29, 31, 32. Не понятно что то. Проблема с кнопками с 17 по 32. Что то с прошивкой или у меня?

**Comment by vsulako** [comment]
Кнопки на регистрах HC165? Проверил у себя, ничего такого нет. Наверное, что-то в соединениях.

**Comment by lazenyuk-dmitry** [comment]
> Кнопки на регистрах HC165? Проверил у себя, ничего такого нет. Наверное, что-то в соединениях.
> 

Да на регистрах HC165... Странно. Вроде как то проверял было нормально.... Вроде бы.

**Comment by lazenyuk-dmitry** [comment]
@vsulako я нашел баг. Смотри регистры работают по парно можно сказать. Баг проявляется если подключить все кнопки, то есть все 4 регистра. Проблема проявляется при постоянном зажатии одной, двух кнопок. 

1. Подключите все 4 регистра все 32 кнопки.
2. На одном из регистров зажмите одну или две кнопки на постоянно. 
3. На втором парном регистре понажимайте кнопки, при нажатии некоторых кнопок проявляется баг. То есть если зажали на постоянно кнопки 17-24 то при нажатии некоторых кнопок 25-32 будут глючить кнопки. 

Если подключить только кнопки 1-16 то этот баг я не видел. Проверьте пожалуйста. У меня вроде последняя версия прошивки и GUI.

**Comment by vsulako** [comment]
У меня не повторяется. Зажимаю 17-18, все 25-32 работают как ожидается, хоть по одной, хоть все вместе.
Проверьте нет ли плохого контакта на линии PL (ножки 1 на микросхемах, желтые линии на схеме) и на линии от ножки 10 первого регистра на ножку 9 второго (оранжевый цвет на схеме). 
Возможны глюки, если второй регистр в цепочке отсутствует, но у вас как я понимаю все четыре на месте.

**Comment by lazenyuk-dmitry** [comment]
А PL SCK никак не прозвонить мультиметром? Начал прозванивать провода, да вроде все нормально... Не понятно в чем дело.

**Comment by vsulako** [comment]
К сожалению, мультиметром  разве что только прозвонить. А посмотреть что там происходит - это нужно осциллограф с памятью, а лучше логический анализатор.
Кнопки 1-16, когда подключены отдельно, работают правильно?

**Comment by lazenyuk-dmitry** [comment]
Я вообще не понимаю в чём дело. Все правильно вроде. 

![IMG20220913003049.jpg](https://user-images.githubusercontent.com/31993282/189895828-abf6fdc9-e3b0-4a4b-9503-9858fe160986.jpg)
![IMG20220913003046.jpg](https://user-images.githubusercontent.com/31993282/189895885-a1dd2eb8-f309-4348-b73f-30b1769cf59f.jpg)

Вот так вот все у меня распаяно на регистрах. Больше вроде и путаться нечему. 

Все нормально работает но вот кнопки 25-32 ни в какую. Бесовщина какая то.

**Comment by lazenyuk-dmitry** [comment]
> Кнопки 1-16, когда подключены отдельно, работают правильно? 

1-16 все правильно... А не может быть то что у меня длинный кабель до КПП? 130 см кабель. Может конденсатор нужно больше припаять? Или что? Я уже не знаю.

**Comment by lazenyuk-dmitry** [comment]
Попробовал конденсатор больше... Такая же фигня.

**Comment by vsulako** [comment]
Да, 104 это 100нф. Его должно быть вполне достаточно. 
Впрочем для проверки можно попробовать подключить проводами покороче.
Именно 25-32 не работают? А 17-24 как?
Попробуйте подключить заведомо рабочую цепочку, которые у вас сейчас на 1-16 на место 17-32, и посмотреть как будет работать. Вроде у вас там разъем на них есть так что это должно быть несложно.

**Comment by lazenyuk-dmitry** [comment]
> Именно 25-32 не работают? А 17-24 как?

Да вот пока не трогаю 25-32 все нормально вроде. Например зажимаю 18-19 все норм. Жму 27 гаснут 18-19 и загораются 27, 29-30.

**Comment by lazenyuk-dmitry** [comment]
> которые у вас сейчас на 1-16 на место 17-32

Это блин сложно будет... Я уже поменял регистры на 17-32 кнопках.

**Comment by lazenyuk-dmitry** [comment]
Да нет... Вроде не может быть такого я уже и кнопки отпаял. Причем если кнопки 17-24 не трогать то 25-32 работают нормально...

**Comment by lazenyuk-dmitry** [comment]
Поменял местами линии data1 и data2 результаты такие же только наоборот. Теперь глюки на кнопках 1-16

**Comment by lazenyuk-dmitry** [comment]
> И впрямь непонятно.
> А посмотрите мультиметром, что на ногах у регистров когда это происходит.
> Зажать 18, 19, 27, чтобы 18-19 погасли и загорелись 27,29,30 и посмотреть какое напряжение на ножках соответствующих 18,19,27,29,30. По идее на тех кнопках что действительно нажаты должно быть 0, а на ненажатых около +5.  Вряд ли будет иначе но вдруг.

Да все так и есть как и ожидается...

**Comment by vsulako** [comment]
Выходит, глюки привязаны именно к этой цепочке регистров, что-то там не так.
Насчет длины кабеля - непонятно. По идее не должно так быть, но надо пробовать, подключите проводами покороче.
Может, все разобрать и снова собрать? Поменяв местами регистры например

**Comment by lazenyuk-dmitry** [comment]
Нашел я кажется в чем дело.... От части вы были правы... Это провод PL. Я кинул перемычку 20см от базы до КПП на PL линию и все вроде стало работать корректно. 

Что делать?

**Comment by vsulako** [comment]
То есть если подключить другими проводами то все работает? Может, с длинным кабелем что-то не так, один провод скажем перебит где-то?

**Comment by lazenyuk-dmitry** [comment]
> То есть если подключить другими проводами то все работает? Может, с длинным кабелем что-то не так, один провод скажем перебит где-то? 

Сомневаюсь.. я использую провода от интернет кабеля покупал в магазине. И я их уже звонил. Я только на PL сделал перемычку и все. Может не хватает мощи?

Щас прозвонил провод на PL все ок. Выходит дело в длине.

**Comment by vsulako** [comment]
Странно что SCK работает а PL нет.  А сопротивления у всех жил одинаковые? она может звониться но иметь большое сопротивление. Если там есть запасные жилы можно другую взять, или несколько в параллель. 
И еще непонятно почему глючит именно после нажатия кнопки.  Сопротивления резисторов на кнопках какие?

**Comment by vsulako** [comment]
Проверьте заодно и эти резисторы, вдруг там какой бракованный попался.

**Comment by lazenyuk-dmitry** [comment]
> Проверьте заодно и эти резисторы, вдруг там какой бракованный попался. 

Проверял. На кнопках резисторы 8.9, 9.15, 10. Ну это я думаю погрешность. И норма. Наверно)

Провода жилы что PL что SCK 1ом сопротивление. Не в силах дело.

**Comment by lazenyuk-dmitry** [comment]
Нельзя там просто подтяжку сделать? Или что?

**Comment by vsulako** [comment]
Да попробовать можно, только не уверен что поможет. Еще один резистор 1-10к с PL регистра к +5в. Хуже быть не должно, во всяком случае.

**Comment by lazenyuk-dmitry** [comment]
> Да попробовать можно, только не уверен что поможет. Еще один резистор 1-10к с PL регистра к +5в. Хуже быть не должно, во всяком случае. 
> 
> а так-то можно вообще обойтись без PL, поставив еще резистор, диод и конденсатор. 

Блин ну кажется все работает. На 10к не помог а на 1к все пошло. Можно даже не на сами регистры а на линию PL прицепить подтяжку. А как подобрать сопротивление? Или это собо ни на что не влияет? 

На SCK тоже можно подтяжку сделать? Я погугли немного вроде подтяжки можно и на PL и SCK сделать. Что то похожее находил. Можете это узнать? Если что можно ссылочку или картинку. 

Я на днях буду все в порядок приводить. 

Спасибо.

**Comment by lazenyuk-dmitry** [comment]
И не плохо было бы добавить подтяжки в документацию.

**Comment by vsulako** [comment]
Можно и на SCK. Точно так же - через резистор к 5в. Хуже не будет. С 1к работает - ну и ладно, чего там еще подбирать. обычно для сигналов годится что угодно в районе 1-50к (выше уже помехи может ловить, а ниже - потребление становится ощутимым)
Вообще я в недоумении. Подтяжки там не должны требоваться нигде кроме кнопок, выход ардуино должен без проблем справляться. Попробовал у себя на двухметровом кабеле - все работает. Правда, у меня регистры в SMD исполнении, но по моему разницы быть не должно. И PL с SCK сигнальные входы, потреблять должны самый мизер. Не понимаю.

**Comment by lazenyuk-dmitry** [comment]
Я тоже не знаю почему так) но ещё все соберу с подтяжками и протестирую.

**Comment by lazenyuk-dmitry** [comment]
Пишут вроде что на каких то регистрах есть внутри уже подтяжки) я хз я не сильно электронщик.

**Comment by lazenyuk-dmitry** [comment]
У меня продолжается какая то фигня с кнопками.... Я уже не знаю что делать с ними. Подпаял подтяжки припаял кнопки. Глючат по прежнему. Половина кнопок нормально работает а половина гонит. Поэтому мне показалось что работают. Но на самом деле нет.

**Comment by vsulako** [comment]
может, это микросхема? что если их поменять местами?

**Comment by lazenyuk-dmitry** [comment]
Уже нету идей никаких

**Comment by vsulako** [comment]
Одна цепочка работает а вторая нет.  надо искать чем вторая отличается от первой.
Подключить короткими проводами чтобы исключить влияние кабеля.
временно убрать второй регистр в цепочке, ногу 10 первого притянуть резистором к VCC. Должны работать первые 8 кнопок.
потом подключить второй регистр, без кнопок. все также должны работать первые 8, а вторые 8 - не работать.
потом по одной добавлять кнопки.

**Comment by lazenyuk-dmitry** [comment]
> Одна цепочка работает а вторая нет.  надо искать чем вторая отличается от первой.
> Подключить короткими проводами чтобы исключить влияние кабеля.
> временно убрать второй регистр в цепочке, ногу 10 первого притянуть резистором к VCC. Должны работать первые 8 кнопок.
> потом подключить второй регистр, без кнопок. все также должны работать первые 8, а вторые 8 - не работать.
> потом по одной добавлять кнопки.

А вротой регистр подпаять с подтяжками на кнопки?

**Comment by vsulako** [comment]
Наверное лучше сначала без, а потом их постепенно добавлять. Тогда эти кнопки без подтяжек будут видеться как нажатые.

**Comment by lazenyuk-dmitry** [comment]
Первый регистр в цепочке работает нормально. Подключаю второй на втором включены все кнопки. Тыкаю подтяжку на 3 ногу и все кнопки гаснут, на двух регистрах. И вообще как то второй регистр живёт своей жизнью.

**Comment by lazenyuk-dmitry** [comment]
Вообще все как гирлянда мигает на втором гегистре

**Comment by vsulako** [comment]
А есть возможность заменить второй полностью? вместе с резисторами, проводами - чтобы все другое?

**Comment by lazenyuk-dmitry** [comment]
> А есть возможность заменить второй полностью? вместе с резисторами, проводами - чтобы все другое?

Да. Но я его менял до этого в паре с первым. Почему то даже просто пальцами до ножек дотрагиваясь начинается какая то не понятная фигня.

**Comment by vsulako** [comment]
Без подтяжек реагирование на пальцы - это нормально, для того там подтяжки и нужны.

**Comment by lazenyuk-dmitry** [comment]
Все так же и с другим регистром. Только цепляю подтяжку на 3 ногу. Гаснут пару кнопок на втором регистре и те что были включены на первом тоже гаснут. Бесовщина какая-то.

**Comment by vsulako** [comment]
А до этого первый регистр и другая цепочка работают как положено? отрабатывают все кнопки в любых комбинациях
и только после того как прицепляется подтяжка ко второму регистру, даже без нажатия соответствующей кнопки начинаются глюки?

**Comment by lazenyuk-dmitry** [comment]
> А до этого первый регистр и другая цепочка работают как положено? отрабатывают все кнопки в любых комбинациях
> и только после того как прицепляется подтяжка ко второму регистру, даже без нажатия соответствующей кнопки начинаются глюки?
> 

Да все регистры кроме последнего работают хорошо. Постедний даже если без подтяжек подключить и проживать на остальных кнопки, то на последнем мигают кнопки. Но остальные при этом работают отлично.

**Comment by vsulako** [comment]
Очень странно. С подтяжками что-то не так, что ли? 
Ну а если его подключить без подтяжек и на входы для кнопок подавать GND или VCC?
GND должно включать соответствующую кнопку а VCC гасить. Остальные кнопки на нем могут моргать, но та к которой подключается - должна работать, и не влиять на кнопки на других регистрах.

**Comment by lazenyuk-dmitry** [comment]
> Очень странно. С подтяжками что-то не так, что ли? 
> Ну а если его подключить без подтяжек и на входы для кнопок подавать GND или VCC?
> GND должно включать соответствующую кнопку а VCC гасить. Остальные кнопки на нем могут моргать, но та к которой подключается - должна работать, и не влиять на кнопки на других регистрах.

То же самое. Подаю vcc так же отрубает кнопки другого регистра. Без понятия что делать.

**Comment by vsulako** [comment]
Я тоже... 
Эксперимент: отсоединить от второго регистра поочередно PL, SCK  и ту что идет к 9й ноге. Будет ли также отрубать кнопки у первого?

**Comment by lazenyuk-dmitry** [comment]
Смотри... Почему то иногда нормально работает второй регистр, а  иногда глючит, как будто зависит от того как его держишь. Как будто какие то помехи. 

И есть такой глюк гадание 29-32 тригерит 25-28, то есть нажатие 29 так же нажимает 25 и так далее. Как будто один ряд на регистре тригерит второй. А иногда все нормально работает. Что такое не понимаю.

**Comment by lazenyuk-dmitry** [comment]
То вообще на втором регистре часть кнопок не срабатывает то работает. Не понимаю нифига в чем проблема. Может какие помехи ловит?

**Comment by lazenyuk-dmitry** [comment]
Я не совсем разобрался но там вроде бы есть вроде как цикл который опрашивает регистры. Так вот я читал что стоит делать паузу в опросах небольшую 40мс где то чтобы фильтровать помехи то ли что. У вас это реализовано? Я просто не знаю уже в чем дело.

**Comment by vsulako** [comment]
Если зависит от того как держать то это похоже на плохой контакт. 
Паузы там вообще ни к чему. Это разве что против дребезга на кнопках, но тут явно не то.  У меня работает без пауз, да и у вас три из четырех работают. Очевидно же что проблемный этот четвертый. Если бы была проблема в коде - она проявлялась бы на обеих цепочках. Ну или не переезжала бы при замене цепочек местами.
Пересоберите всю эту часть заново из всего нового, включая провода. Есть же первая цепочка которая работает правильно, вот точно такую же надо сделать вторую. Конденсатор можно пока убрать.

**Comment by lazenyuk-dmitry** [comment]
В чем может быть дело? Я дотрагиваясь до провода PL и все работает тогда.

**Comment by lazenyuk-dmitry** [comment]
Блин похоже что дело в кабеле. У меня кабель от интернета и концевики RJ45, кабель 8 жил проволоки медной. Заменил на кабель от usb простой. И все работает. Ну и он по короче. Что получается что кабель не подходит почему то? А у меня так все хорошо складывалось на этих кабелях и разъёмах... Обидно... Теперь что то переделывать нужно. На интернетовской кабеле работают педали и ручник нормально и остальные оси тоже. У вас какой кабель используется? Мне нужно 8 жил на КПП.

**Comment by lazenyuk-dmitry** [comment]
Ты можешь объяснить почему на витой паре не работает а с обычным usb кабелем работает? Я не понимаю... Вроде провод да провод чего такого...

**Comment by lazenyuk-dmitry** [comment]
Странно... Если по два провода витой пары пустить на PL SCK DATA вместо одного то тоже все работает.

Я даже так предполагаю что хватит два провода только на PL и все будет работать. Может у тебя есть идеи по этому поводу) дичь какая то.

**Comment by vsulako** [comment]
У меня кабель телефонный плоский, КСПВ 4х0.4, и телефонные разъемы RJ12. 
Восьмижильная витая пару UTP5 показалась слишком жесткой.
Причин чтобы на UTP5 не работало не вижу вообще никаких. Кроме подозрений что одна из жил повреждена.

**Comment by lazenyuk-dmitry** [comment]
> У меня кабель телефонный плоский, КСПВ 4х0.4, и телефонные разъемы RJ12. 
> Восьмижильная витая пару UTP5 показалась слишком жесткой.
> Причин чтобы на UTP5 не работало не вижу вообще никаких. Кроме подозрений что одна из жил повреждена. 
> 

Я уже менял провод. Оно то работает но глючит.

**Comment by lazenyuk-dmitry** [comment]
Вообще интересно как то... Подключаю DATA и PL на одну пару, то есть голубой и бело-голубой. И у меня глючат кнопки но стоит только перенести подключение на разные витые пары так все отлично работает. Это какие то помехи?

**Comment by lazenyuk-dmitry** [comment]
Я тут уже начал фигнёй страдать. Подрубаю сопротивление 1к 10к в разрыв линии PL и все работает. Ещё можно и на DATA кинуть в разрыв сопротивление. Я не понимаю почему но работает. Думаю даже так и оставить. 


Василий, может быть напишем научную работу по дичи с витой парой? 😄

**Comment by lazenyuk-dmitry** [comment]
Короче установил сопротивление 1к в разрыв PL, все собрал и все работает. Странно. Очень интересно но ничего не понятно. 

Подскажи форум электронщиков где можно задать такой вопрос. Интересно есть ли разумное объяснение этому.

**Comment by vsulako** [comment]
Мне тоже непонятно. Посмотреть бы что там происходит, но нечем. И сам потыкать не могу.
форумы.. ну наверное radiokot.ru easyelectronics.ru cxem.net

**Comment by lazenyuk-dmitry** [comment]
Пробовал играть в Assetto Corsa с КПП все отлично Буг ушел. В разрыв сопротивление 1к на PL.
