### ISSUE TITLE
Проблема с ограничителем

### ISSUE THREAD

**Issue by Darkmen203** [vsulako/AFFBWheel#48]
Здравствуйте! Подключил все руль по схеме (драйвер мотора через пин). По итогу ограничение поворота какое-то слабенькое, больше похоже на импульс короткий, чем сопротивление. Ввиду этого очень легко ограничение перейти и затем сбивается центр. В чем может быть проблема?
Также еще есть проблема что в программе все отображается корректно, пока не зайдешь в игру, как только заходишь в игру, ощущение как будто появлются пропуски при считывании с энкодера и руль в игре и программе начинает вести себя не адекватно

**Comment by Darkmen203** [comment]
использую инскрементальный энкодер(600ppr), мотор 775 и бтс

**Comment by Darkmen203** [comment]
Сейчас ещё попробовал попроверять, получается когда просто условно с рабочего стола заходишь в программу affbwheel gui и пробуешь, не важно насколько быстро/медленно крутишь руль, всегда определяется одинаковое количество оборотов (если не выходить за ограничение)
Зашёл в игру и пробую крутить руль там (проверяю на етс2), итог, при медленной прокрутке как будто бы вообще в игре прогркучивается градусов на 10, когда физически прокрутил на примерно 90, когда кручу быстро как будто бы больше определяет градусов, СВОРАЧИВАЮ игру, оставляя ее активной и через приложение проверяю по итогу:
Во-первых, сбивается центр абсолютно непонятные значения выдает, во-вторых, оборотов становится физических около 6. Закрываю игру и сразу же все становится на свои места и все работает корректно. Настройка на 900 градусов. Не пойму в чем может быть проблема? Соединение напрямую энкодер к плате, могу попробовать через резисторы на 1к подключить. Опять же не думаю что это что-то даст, как будто бы дело всё-таки в чем-то другом, потому что  проблема возникает именно при запущенной игре и исчезает после. Также пробовал в другой(my summer car), там такая же проблема. Как будто бы игра перекалибровывает руль и он перестает работать корректно, но опять же вопрос почему тогда даже при свернутой игре, программатоже начинает криво регать энкодер

**Comment by vsulako** [comment]
Мистика какая то.  
Без обратной связи то же самое?  
Проверьте правильно ли работает ось руля в [VKB Joytester](https://www.vkbcontrollers.com/pages/downloads) или [DXJoyTester](https://sites.google.com/site/diyheadtracking/home/joystick/dxjoytester).  
Если там что-то не то - сбросьте настройки в свойствах контроллера (панель управления, настройка игровых USB контроллеров, свойства-параметры-восстановить)

**Comment by Darkmen203** [comment]
Проверил с помощью DXJoyTester вкладкой Axes. Итог:
    если игра не запущена и просто смотрим данные в этой программе, то FPS в районе 750~, 
    если игру запускаем и сворачиваем и снова просматривает данные с энкодера, то FPS максимум 61.
Думаю, что как раз в этом и проблема, только вот почему такое возникает? И вот самое главное как вообще может быть такое что игра на это влияет

**Comment by Darkmen203** [comment]
![Новый точечный рисунок](https://github.com/vsulako/AFFBWheel/assets/125760866/eae8c8cf-232b-4cba-be2e-05af1e302036)
скрин 1 - игра не запущена
![Новый точечный рисунок](https://github.com/vsulako/AFFBWheel/assets/125760866/7706c5d5-fdd2-4dfe-b4f5-240c5375d290)
скрин 2 - запустил игру и смотрю данные

Также, как вы сказали попробовал отключить ффб, но ничего не поменялось

**Comment by vsulako** [comment]
Игра на FPS влиять особо не должна. У меня при игре ниже 600 не опускается. Разве что создается очень много эффектов ОС, но если это и с отключенной ОС, тогда не знаю.

Эти скрины DXjoytester - руль от края до края, или просто туда-сюда?

В ETS2 есть еще свои настройки которые могут повлиять на поведение руля.

![изображение](https://github.com/vsulako/AFFBWheel/assets/95934592/c4e59d7f-f1d7-4fbe-96f2-25f58bcfc8ab)

Чувствительность руля - макс
Нелинейность руля - мин
порог чувствительность - мин

**Comment by Darkmen203** [comment]
![image](https://github.com/vsulako/AFFBWheel/assets/125760866/88bbabd7-6d22-4586-b9db-0a7123bc8e0d)
а может ли быть проблема тут? это в диспетчере устроиств свойства арудино

**Comment by vsulako** [comment]
Нет, эти свойства ни на что не влияют.

FPS который показывает DXJoytester, похоже, зависит еще и от компьютера, он может скакать без видимых причин.
Реальную производительность контроллера можно посмотреть по команде timing в мониторе порта (число loops/sec).

Вообще игра никак не должна менять работу контроллера. 
Есть ли возможность проверить на другом компьютере?

**Comment by Darkmen203** [comment]
> Вообще игра никак не должна менять работу контроллера. Есть ли возможность проверить на другом компьютере?

как раз этим и занимался)

По результатам, получилось, что там все работает абсолютно идеально, как в игре, так и в DXJoytester.
    Основное что заметил ( за качество изменяюсь)
    
![image](https://github.com/vsulako/AFFBWheel/assets/125760866/f4058520-26bd-41d8-97c0-443a512e8f5d)
на компьютере, в котором все идеально
![image](https://github.com/vsulako/AFFBWheel/assets/125760866/2cff2866-266f-4533-aba0-412a84769f60)
на компьютере с проблемой, при этом не понятно в чем причина.
    Основные отличия, что тот комп, на котором работает более старый и там не установлена ардуино ide. Ну в остальном не знаю что именно могло повлиять(

**Comment by Darkmen203** [comment]
в компе с этой проблемой уже в разные порты пробовал, завтра попробую еще один компьютер, но в него вставлю диск с виндой проблемного компьютера, посмотрим что будет! Ну в любом случае это поможет исключить проблему винды, хех

**Comment by Envi4** [comment]
А пробовали на компьютере с которым проблема, отключать все устройства ввода, может с каким-то устройством происходит конфликт

**Comment by Darkmen203** [comment]
> А пробовали на компьютере с которым проблема, отключать все устройства ввода, может с каким-то устройством происходит конфликт

Хм, интересный вариант, завтра проверю, тебе пробовал отключать все устройства, т.к. будет тяжело проверить, но я попробую завтра что-то придумать чтобы остался только один руль

**Comment by Darkmen203** [comment]
Решил проблему с неправильным поворотом, оказалось что дело в BIOS там была настрока LPT порта и стояло что-то типо
STD Printer Mode . Изменил на spp и все заработало. Спасибо большое за помощь)
А я уже все перепробовал все кроме материнки ставил в другой компьютер, а надо было просто с BIOS поиграться)
    Остался один вопрос по endstop, получается когда доходишь до границы очень медленно, то прям хорошо стопит, но в случае если около 400 градусов когда просто руками крутить дальше быстро, то проходишь границу и там ограничитель просто подает импульсами короткими напряжение и все, но руль не стопит. Заметил что это работает так, ограничение по параметру row примерно 10200 и на нем хорошо стопит, но если случайно прошел эту границу на скорости, то оказываешься примерно на 10400, то там уже руль не жестко стопится, а просто пытается с помощью короткого импульса вернуться (которые на самом деле очень слабый, почти не заметный.
    
![image](https://github.com/vsulako/AFFBWheel/assets/125760866/be3bc683-67b0-44b8-bf27-8d9329368b9a)
Пробовал с такими настройками и + пытался поиграться с значениями параметров endstop

**Comment by vsulako** [comment]
Что-то странное.  
Через монитор порта дайте команду fvaout и покажите график из DXJoytester, что происходит при прохождении границы.  
Значение ОС будет на оси rz.  
Должно быть как то так:  
![изображение](https://github.com/vsulako/AFFBWheel/assets/95934592/8592f8c9-d3a2-4b83-9458-684c580a4732)

Также включите вывод по оси X - `axisinfo 0` и посмотрите, какие там получаются значения у FFB. Должно быть  16383 или -16383.

**Comment by vsulako** [comment]
Странно. На вид более-менее правильно, только непонятно почему упирается в 16382 а не 16383, и почему в dxjoytester не доходит до максимума. Пики, наверное, из-за работающего мотора. А если настройки (усиление, min/max force) установить на исходные?

**Comment by Darkmen203** [comment]
![image](https://github.com/vsulako/AFFBWheel/assets/125760866/21a33264-1d8e-48ae-ace4-eab044c942ae)
сейчас поставил на такие значения, не помню какие были исходные...
В 16382 упирается потому что почему-то не выставляется 16383, когда ввожу это число стирается последняя цифра в приложении

**Comment by Darkmen203** [comment]
сейчас через serial monitor выставил 16383

**Comment by Darkmen203** [comment]
![image](https://github.com/vsulako/AFFBWheel/assets/125760866/daac98df-b3fe-47bf-aa16-33aa12280b18)
![image](https://github.com/vsulako/AFFBWheel/assets/125760866/d18207fd-9d52-4494-9b07-ab422152d2d4)
но при этом все равно когда вправо крутишь не получилось добиться 16383

**Comment by vsulako** [comment]
Не получается повторить.
Можете выложить исходник прошивки который у вас загружен?

**Comment by Darkmen203** [comment]
[AFFBWheel-master_Darkmen_set.zip](https://github.com/vsulako/AFFBWheel/files/13981383/AFFBWheel-master_Darkmen_set.zip)
вот мой исходник

**Comment by Darkmen203** [comment]
У меня как будто бы импульсами работает и как будто бы не на 100% зажимает, а на 80, по сравнению с вашим графиком

**Comment by vsulako** [comment]
Чертовщина какая то. И с этим исходником все работает как должно. 
Выложите еще бинарный (скетч/экспортировать бинарный файл). В исходнике такой есть, с ним тоже работает нормально, но по моему, там немного другие настройки.
А как с другими эффектами? Если в FEdit создать эффект Constant с макс усилием - тоже импульсами на 80%?
И еще попробуйте без пина EN, в BTS выводы R_EN/L_EN посадить на +5v.

**Comment by Darkmen203** [comment]
Ну сейчас я в итоге попробовал замерить блок питания, который использовал (12v 6.97A). В итоге оказалось что блок присаживается в момент нагрузки с 11.53v до 5v, решил пробовать другие блоки питания(использовал компьютерные)
1. Подключил блок питания 12v 17A.
          Мотор стал хорошо держать не импульсами, но если силой пройду ограничение, то мотор начинает сходить с ума и бесконечно крутить влево( при этом в программе обратно не выходит с границы), отключение блока питания и все становится на свои места, в программе сразу же определяет положение и все четко.
2. Подключил другой блок питания 12v 14A.
       И все отлично, полностью все хорошо работает, с ума ничего не сходит.

Итог: получается что блок питания должен быть чуть с запасом, но не сильным, если переборщить, то можно сгореть, хех, потому что теперь вся комната пропахлась запахом оплётки мотора хех. Не знаю так и должно быть или нет. Но все же получается также когда подключил блок питания 14А померил сколько было в пике ампер(подключением мультиметра в разрыв плюса), показалось 8а и при начале нагрузки около 7а. Т.е. итог минимум 10А для более менее нормлаьной работы, но кто ж знал

**Comment by vsulako** [comment]
775 не должен столько потреблять. Тем более что еще и воняет. Он так сгорит.  
У меня 775 с12в (а сам двигатель на 24),  и редуктор 1:25.  так когда просто крутит - потребляет ~250ма, а при блокировке - около 2а.  
Ему ничего там не мешает? может закусывает где-то?

**Comment by Darkmen203** [comment]
У меня 775 12в, воняет только когда я соединил с блоком 17ампер и когда завел за огранку с большим усилием и он начал с ума сходить, с 14амперами все нормально)

**Comment by Darkmen203** [comment]
Ну у меня он не закусывает, просто стоит в соотношении 1:4 и на основном валу руль от defender adrenaline mini, получается что мб вес большой, хотя в планах ставит руль от реальной машины, поэтому он должен этот уж точно выдерживать, впринципе вот от 10ампер ему норм было бы)

**Comment by Darkmen203** [comment]
Хм, очень странно, мб у меня какой-то неправильный 775

**Comment by vsulako** [comment]
Ну они вообще разные бывают. 
https://ae01.alicdn.com/kf/HTB15etNXPzuK1RjSspeq6ziHVXaR.jpg
https://ae01.alicdn.com/kf/HTB1EPjabBiE3KVjSZFMq6zQhVXaC.jpg

**Comment by Darkmen203** [comment]
Извините, не видел ваше сообщение, все блок пытаюсь найти) Хорошо попробую сегодня замерить без нагрузки. Параллельно делал коробку передач и столкнулся с вопросом: будет 7-9 кнопок, хотел соединять их по схеме APB первый вариант, единственное, резистор подтягивающий от питания у меня больше (220ком) и вот проблема в данный момент соединил 7 кнопок и не пойму по какому принципу должно работать АЦП? У меня при отключении от пина аналогового провода seri monitor выдает 165 ( я думал что должно быть 0 или 255) и ещё вопрос vcc к 5v подключать?

**Comment by Darkmen203** [comment]
> Ну они вообще разные бывают. https://ae01.alicdn.com/kf/HTB15etNXPzuK1RjSspeq6ziHVXaR.jpg https://ae01.alicdn.com/kf/HTB1EPjabBiE3KVjSZFMq6zQhVXaC.jpg
> 
> А есть возможность его снять и измерить ток без нагрузки?

Замерил вообще без нагрузки 0.6а

**Comment by Darkmen203** [comment]
@vsulako сейчас еще раз все поменял, нашел резистор как на схеме (100 Ком), VCC подключил к 5V, GND к GND. Единственное заметил, что случайно купил на 4.7 Ком резисторы к кнопкам. Попробовал замерить мультиметром что происходит и значения почему-то не меняются. И вот вопрос, правильная ли схема? (В интернете большинство схем по-другому выглядят. И как расчитать какие должны быть резисторы, как правильно проверить? У меня АЦП вообще не меняется.

**Comment by Darkmen203** [comment]
в целом сейчас более менее нормально все, но буду увеличивать отношение вала к рулю. Еще есть доп вопрос, есть ли возможность возврата руля к центру аля как в logitech, только засчет двигателя. Т.е. чтобы это можно было настроить отдельно от игры?

**Comment by vsulako** [comment]
нет, постоянных эффектов нет.

**Comment by Darkmen203** [comment]
Понял, спасибо, все остальные проблемы решил путем изменения соотношения шкивов, преднатяжителем и установкой другого БП. Остальное пока в планах, а именно сделать кнопки на спорт руль, лепестки и педали. Потом мб покажу, если будет все красиво сделано) Пока что хаос)
