### ISSUE TITLE
Добавление ещё одного джойстика на Pro Micro

### ISSUE THREAD

**Issue by alivergg** [vsulako/AFFBWheel#64]
Можно ли убрать линию PL(как указано в документации), перекинуть пины для управления драйвером на 3 и 5 цифровые пины(у них есть PWM) и докинуть ещё 1 джойстик на пины A9 A10(9 и 10 пины аналоговые)?

**Comment by vsulako** [comment]
Нет. Во первых, пины управления драйвером нельзя так просто поменять, там управление не через analogWrite, а через таймер 1, у которого выходы на пины 9-10. 
Во вторых, у контроллера все равно может быть не больше 8 осей (больше Windows не увидит).
