### ISSUE TITLE
Помехи от отключенных осей.

### ISSUE THREAD

**Issue by lazenyuk-dmitry** [vsulako/AFFBWheel#9]
Привет. Я тут начал собирать базу. Планирую еще сделать КПП которую можно будет отключать и подключать. И у меня еще остается свободная одна ось. Я думаю вынести оставшиеся кнопки на КПП и ось как крутилку, может пригодиться. Но я так понимаю что я буду ловить помехи если не подключу КПП с этой осью? А оси отключаются только в прошивке или замыканием на минус? Можно ли что то с этим сделать? Или можно было бы возможность в GUI отключить оси.

**Comment by vsulako** [comment]
да запросто. Можно в прошивке, можно замыканием на минус, а можно и в  GUI - просто поставьте для оси максимум равным минимуму и все.
